### ISSUE TITLE
Follow namespace conventions

### ISSUE THREAD

**Issue by v0dro** [gau27/spice_rub#1]
If the repo name is spicerub the class should be `Spicerub`: http://guides.rubygems.org/name-your-gem/

**Comment by gau27** [comment]
Thank you for pointing that out, I've modified it in the spec. Does the name on the ReadMe have to follow this convention?

**Comment by zverok** [comment]
In fact, I think SpiceRub is better-looking name, but then the gem (and, preferably, the repo) should be renamed to spice_rub.

**Comment by v0dro** [comment]
Yes the convention should follow throughout the gem repo.

**Comment by gau27** [comment]
This has been resolved.
