### ISSUE TITLE
More tests needed

### ISSUE THREAD

**Issue by mohawkjohn** [gau27/spice_rub#10]
I'm seeing that you've written additional methods, but I'm not seeing tests to match those. You want to have tests because soon your library will be too large to check everything by hand. Additionally, tests can help alleviate confusion about how functions are supposed to work — particularly when you come back and look at something a year later and can't remember any longer.

**Comment by gau27** [comment]
All native functions will be tested in this file : - https://github.com/gau27/spice_rub/blob/master/spec/native_spec.rb
