### ISSUE TITLE
Get nmatrix C headers from gem

### ISSUE THREAD

**Issue by v0dro** [gau27/spice_rub#11]
spice_rub places the nmatrix C headers in the ext folder itself. If the NMatrix C API changes and the gem dependency is updated, this will most probably cause a hard to trace bug in the gem. It would be better to load the header files from where nmatrix has been installed.

See this example in rb-gsl: https://github.com/SciRuby/rb-gsl/blob/master/ext/gsl_native/extconf.rb#L154

**Comment by gau27** [comment]
After much tinkering around, settled on something that works and looks elegant. 

https://github.com/gau27/spice_rub/blob/master/ext/spice_rub/extconf.rb#L6,L12
