### ISSUE TITLE
'rake install' Doesn't work

### ISSUE THREAD

**Issue by gau27** [gau27/spice_rub#13]
Today I realized that `rake install` doesn't properly load all the files inside the lib directory when require is called. Everything works perfectly with `rake pry` from inside the source gem folder, but using pry or irb outside the gem directory causes the following strange behavior :-

```ruby
[2] pry(main)> require 'spice_rub'
=> true
[3] pry(main)> SpiceRub::Native
NameError: uninitialized constant SpiceRub::Native
from (pry):4:in `__pry__'


[4] pry(main)> require 'spice_rub/spice_rub.rb'
=> true

[5] pry(main)> SpiceRub::Native
NameError: uninitialized constant SpiceRub::Native
from (pry):6:in `__pry__'

 
[7] pry(main)> SpiceRub::KernelPool
=> SpiceRub::KernelPool

[8] pry(main)> require 'spice_rub/spice_rub.so'
=> true

[9] pry(main)> SpiceRub::Native
=> SpiceRub::Native
```

I'm unsure how to fix this, I've been trying to tweak the gemspec related files, @mohawkjohn , any idea on what could be the problem here?

**Comment by gau27** [comment]
Okay so I tried manually building and installing the gem and the same issue occurs so this isn't really a problem with rake.

**Comment by mohawkjohn** [comment]
@gau27 Do the files exist inside of the gem package? Sometimes you have to specify a manifest of files to actually include, and if that manifest is out of date, files won't be included. A lot of people just generate the manifest using the git index. NMatrix does so manually.

**Comment by gau27** [comment]
@mohawkjohn 

All the Ruby files are present in the `pkg` folder (I'm not sure if that's what you mean) , but since I can load the entire gem by typing `require 'spice_rub/spice_rub.rb' ` and require 'spice_rub.so'` after `require 'spice_rub'` , doesn't that mean all files are up to date on the manifest? 

I noticed that there's no spice_rub.so inside the pkg/ folder though.

**Comment by gau27** [comment]
Okay so  there was a stray `spice_rub.so` lying around in one of my RVM extensions folders that was probably created during the time I was using `extconf.rb` and `make` manually. For some reason it overrides the default gem path and thus was loading a really early `spice_rub.so` file (there was even a `spicerub.so` file in here  =) ) even after uninstalling them gem. `rake install` works fine now :)
