### ISSUE TITLE
Make tests more specific and use latest RSpec conventions

### ISSUE THREAD

**Issue by v0dro** [gau27/spice_rub#2]
The exception raising tests [here](https://github.com/gau27/spicerub/blob/master/spec/kernel_spec.rb#L21) aren't specific enough. Which error is being raised?

Also, follow the latest RSpec `let` and `subject` methods in your specs. You can find samples in the daru specs Lokesh is writing [here](https://github.com/v0dro/daru/pull/134/files#diff-447878c3f829efdf214b2e4db4d1c231R690).

Do follow these guidelines throughout your project to make it more maintainable in the future.

**Comment by gau27** [comment]
Hi, I'll get on this and figure it out before tonight

**Comment by gau27** [comment]
Spec style is getting better. (I hope)
