### ISSUE TITLE
About inclusion of binaries in gem

### ISSUE THREAD

**Issue by v0dro** [gau27/spice_rub#5]
According to [this folder](https://github.com/gau27/spice_rub/tree/master/ext/spicerub/cspice/lib) it looks like you're including ready made binaries of cspice in the gem. What if the architecture the user wants to use the gem on is not the same as yours?

The library should ideally be decoupled from the wrapper and we should let the user install cspice however he/she wants and then simply use the Ruby wrapper with a gem install. If you must keep the binaries, you should configure your extconf such that it falls back to a user installed version of cspice if it's available and raises appropriate errors if there's an incompatibility between the supplied binaries and the user's computer.

@mohawkjohn your thoughts?

**Comment by zverok** [comment]
My 5c (they are everywhere!)
For "rare" libraries (which are doubtful to be already installed, or have prebuilt packages for the popular OSes) I've seen several times the target library _sources_ included into gems `ext` folder, and gem installation builds _both_ the target library and gem wrapper around it. That seems pretty convenient, like you want to play with Spice and Ruby, you just do `gem install spice_rub`. Though, in our case counter-argument may be that CSPICE has 48 MiB of sources, I'm not sure it is appropriate to place them all into a gem :(

**Comment by gau27** [comment]
@zverok :

I don't plan on shipping these binaries, ideally there'll be a script that
searches for a local installation or downloads the correct one. This is my
local config and I'm not sure why it got pushed because  I added *.a to my
.gitignore. I'll reach home in an hour so I'll get it fixed then.

**Comment by mohawkjohn** [comment]
I realize inclusion of binaries was intentional, but I want to add that I think it might be best to use `git submodule` to include the SPICE sources instead of having a copy in-tree. It doesn't have to be done now, but it's something to research and think about.

**Comment by mohawkjohn** [comment]
See #7 (and close this one).
