### ISSUE TITLE
Don't use Kernel as a class name

### ISSUE THREAD

**Issue by mohawkjohn** [gau27/spice_rub#6]
I strongly advise against using `Kernel` as a class name, since it's already used by Ruby core. Call it `SpiceKernel` instead.

**Comment by gau27** [comment]
I thought it'd be okay to hide it as a private constant which only KernelPool interacts with but it seems nothing is truly invisible in Ruby. I'll change it to SpiceKernel

**Comment by gau27** [comment]
Fixed as of commit https://github.com/gau27/spice_rub/commit/6c851defaa8c17b5ef000eb5fb954ab2945eed56 (Forgot to tag it in the commit message)
