### ISSUE TITLE
C identifiers should have prefixes

### ISSUE THREAD

**Issue by mohawkjohn** [gau27/spice_rub#8]
Since you're writing in C and don't have namespaces, you should really prefix your global C functions and identifiers (e.g., SHORT, LONG, EXPLAIN, ALL, unload, etc).

```
#define SPICE_SHORT 0
```
for example. You could also call it RUB_SHORT if you want something easier to type.

That way it doesn't cause a namespace collision. (However, if you're using `SHORT` because it's used this way in the SPICE code, it's fine. Please add a comment if that's the case.)

For stuff like `furnsh`, you also need a prefix — UNLESS you want to declare the function `static`. If you make it static, it won't be visible to other sources during compilation; it'll only be available within spice_rub.c.

So, either of these:
```
static VALUE unload(...)
```
or
```
VALUE rub_unload(...)
```

Make sense?

**Comment by mohawkjohn** [comment]
If you're planning on using C++ as well, please let me know, as there are other options in that case.

**Comment by gau27** [comment]
Is there any crucial drawback in using the STATIC alternative? Prefixing the function names could make the native API more messy than it needs to be (if someone wants to use the native C spice API for anything other than kernel handling)

**Comment by mohawkjohn** [comment]
Nope, NMatrix API is available in C or C++.

I think `static` is great. I use it every chance I get. The drawback is that functions you declare static won't be accessible from other object files — but that's also the main feature.

You'll probably still need to prefix functions you can't afford to declare static.

**Comment by gau27** [comment]
changed to static

**Comment by gau27** [comment]
@mohawkjohn  @v0dro 

Since static members aren't available to other sources during compilation, I can't modularize the extension code by placing it in separate file because attachment of functions to top level modules occurs only within `spice_rub.c` .

This is going to make `spice_rub.c` a rather large file in itself, something I noticed while reviewing the symengine.rb gem which has multiple files placed in the `ext` folder.  Is there any workaround for this?

**Comment by gau27** [comment]
Removed static and prefixed all C functions. [commit #59] (https://github.com/gau27/spice_rub/commit/59fd0ddff7ca40567663549aea164b4f9addc7cb)
